/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./dashboard.html", "./js/dashboard.js"],
  safelist: [
    "bg-red-100",
    "text-red-600",
    "bg-indigo-100",
    "text-indigo-600",
    "bg-slate-100",
    "text-slate-500",
    "bg-emerald-100",
    "text-emerald-700",
    "bg-amber-100",
    "text-amber-700",
    "bg-blue-100",
    "text-blue-600",
    "border-indigo-500",
    "bg-indigo-50",
    "border-indigo-200",
    "border-indigo-300",
    "ring-2",
    "ring-indigo-200",
    "border-slate-300",
    "bg-red-50",
    "border-red-200",
    "bg-slate-50",
    "border-slate-200",
    "text-red-700",
    "text-indigo-700",
    "text-slate-600",
    "bg-red-500",
    "bg-indigo-500",
    "bg-slate-400",
    "group-hover:border-indigo-500",
    "group-hover:opacity-100",
    "line-through",
    "text-slate-400",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Noto Sans KR"', "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
